In [6]:
#from numpy.core.numeric import infty
!pip install numpy
!pip install pandas
!pip install plotly

!pip install scikit-learn # non-depreaceated sklearn

You should consider upgrading via the 'c:\users\friso\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.


You should consider upgrading via the 'c:\users\friso\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.


You should consider upgrading via the 'c:\users\friso\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.
ERROR: Invalid requirement: '#'
You should consider upgrading via the 'c:\users\friso\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.


Task 1

In [7]:
import pandas as pd
# read the csv and make it a pandas.DataFrame
frame = pd.DataFrame(pd.read_csv("./online_shoppers_intention.csv"))
frame.describe(include='all') # 18 columns, including 2 categorical: Month & VisitorType, and two boolean: Weekend & Revenue

Administrative  Administrative_Duration  Informational  \
count     12330.000000             12330.000000   12330.000000   
unique             NaN                      NaN            NaN   
top                NaN                      NaN            NaN   
freq               NaN                      NaN            NaN   
mean          2.315166                80.818611       0.503569   
std           3.321784               176.779107       1.270156   
min           0.000000                 0.000000       0.000000   
25%           0.000000                 0.000000       0.000000   
50%           1.000000                 7.500000       0.000000   
75%           4.000000                93.256250       0.000000   
max          27.000000              3398.750000      24.000000   

        Informational_Duration  ProductRelated  ProductRelated_Duration  \
count             12330.000000    12330.000000             12330.000000   
unique                     NaN             NaN                      NaN   
top                        NaN             NaN                      NaN   
freq                       NaN             NaN                      NaN   
mean                 34.472398       31.731468              1194.746220   
std                 140.749294       44.475503              1913.669288   
min                   0.000000        0.000000                 0.000000   
25%                   0.000000        7.000000               184.137500   
50%                   0.000000       18.000000               598.936905   
75%                   0.000000       38.000000              1464.157214   
max                2549.375000      705.000000             63973.522230   

         BounceRates     ExitRates    PageValues    SpecialDay  Month  \
count   12330.000000  12330.000000  12330.000000  12330.000000  12330   
unique           NaN           NaN           NaN           NaN     10   
top              NaN           NaN           NaN           NaN    May   
freq             NaN           NaN           NaN           NaN   3364   
mean        0.022191      0.043073      5.889258      0.061427    NaN   
std         0.048488      0.048597     18.568437      0.198917    NaN   
min         0.000000      0.000000      0.000000      0.000000    NaN   
25%         0.000000      0.014286      0.000000      0.000000    NaN   
50%         0.003112      0.025156      0.000000      0.000000    NaN   
75%         0.016813      0.050000      0.000000      0.000000    NaN   
max         0.200000      0.200000    361.763742      1.000000    NaN   

        OperatingSystems       Browser        Region   TrafficType  \
count       12330.000000  12330.000000  12330.000000  12330.000000   
unique               NaN           NaN           NaN           NaN   
top                  NaN           NaN           NaN           NaN   
freq                 NaN           NaN           NaN           NaN   
mean            2.124006      2.357097      3.147364      4.069586   
std             0.911325      1.717277      2.401591      4.025169   
min             1.000000      1.000000      1.000000      1.000000   
25%             2.000000      2.000000      1.000000      2.000000   
50%             2.000000      2.000000      3.000000      2.000000   
75%             3.000000      2.000000      4.000000      4.000000   
max             8.000000     13.000000      9.000000     20.000000   

              VisitorType Weekend Revenue  
count               12330   12330   12330  
unique                  3       2       2  
top     Returning_Visitor   False   False  
freq                10551    9462   10422  
mean                  NaN     NaN     NaN  
std                   NaN     NaN     NaN  
min                   NaN     NaN     NaN  
25%                   NaN     NaN     NaN  
50%                   NaN     NaN     NaN  
75%                   NaN     NaN     NaN  
max                   NaN     NaN     NaN

Verhaaltje van ~1min

In [8]:
#visualisation
# split the Browser 13 users from the rest
frame13 = frame.loc[frame.Browser == 13]
frameOther = frame.loc[frame.Browser != 13]

import plotly.graph_objects as go
# make a small dataframe with normalized data for plotting
def create_distribution(frameColumn):
    return pd.DataFrame({
        'Browser 13': frame13[frameColumn].value_counts(normalize=True),
        'Other browsers': frameOther[frameColumn].value_counts(normalize=True)
    }).reset_index().rename(columns={'index': col})
# plot all these columns
for col in ['VisitorType', 'Region', 'Month']:
    distribution = create_distribution(col)
    fig = go.Figure()
    fig.add_trace(go.Bar(x=distribution[col], y=distribution['Browser 13'], name='Browser 13'))
    fig.add_trace(go.Bar(x=distribution[col], y=distribution['Other browsers'], name='Other browsers'))
    fig.update_layout(barmode='group', title=f'{col} Distribution')
    fig.show()

Task 2

In [9]:
#Prepositioning op basis van algoritmes in task 3
# Preprocess using dropna AND change all string types to an integer
def Month_to_num(x):
    months = {
        "Jan": 1, "Feb": 2, "Mar": 3, "Apr": 4,
        "May": 5, "June": 6, "Jul": 7, "Aug": 8,
        "Sep": 9, "Oct": 10, "Nov": 11, "Dec": 12, "Returning_Visitor": 1, "Old_Visitor": 2, "New_Visitor": 3, "Other": 4, True: 1, False: 0}
    if x not in months:
        raise ValueError(f"Invalid month string: {x}")
    return months[x]


addlist = []
preprocessed = (frame.copy().dropna())
for i, j in enumerate(preprocessed['Month']):
    addlist.append(Month_to_num(j))
preprocessed['Month'] = addlist

addlist = []
for i, j in enumerate(preprocessed['VisitorType']):
    addlist.append(Month_to_num(j))
preprocessed['VisitorType'] = addlist

addlist = []
for i, j in enumerate(preprocessed['Weekend']):
    addlist.append(Month_to_num(j))
preprocessed['Weekend'] = addlist

addlist = []
for i, j in enumerate(preprocessed['Revenue']):
    addlist.append(Month_to_num(j))
preprocessed['Revenue'] = addlist

for i in preprocessed.columns:
    preprocessed[i] = pd.to_numeric(preprocessed[i], errors='raise')

print(preprocessed)




       Administrative  Administrative_Duration  Informational  \
0                   0                      0.0              0   
1                   0                      0.0              0   
2                   0                      0.0              0   
3                   0                      0.0              0   
4                   0                      0.0              0   
...               ...                      ...            ...   
12325               3                    145.0              0   
12326               0                      0.0              0   
12327               0                      0.0              0   
12328               4                     75.0              0   
12329               0                      0.0              0   

       Informational_Duration  ProductRelated  ProductRelated_Duration  \
0                         0.0               1                 0.000000   
1                         0.0               2                64.000000 

Task 3

In [10]:
# affinity propagation clustering - aan de hand van documentatie - NU HEEL SLOOM
from sklearn.cluster import AffinityPropagation, DBSCAN, Birch
Data = preprocessed.copy()
#Gebruik van sample maakt het proces sneller
Sample = Data.sample(n=1000)
clustering = AffinityPropagation(random_state=5).fit(Sample)
AffinityPropagation(random_state=24)

labels = clustering.labels_
cluster_centers = clustering.cluster_centers_
n_clusters = len(cluster_centers)

print("Number of clusters:", n_clusters)
print("Cluster centers:\n", cluster_centers)


# DBSCAN clustering
#TODO werkt maar de label -1 laat zien dat er een hoop data punten in ruis categorie vallen...
clustering2 = DBSCAN(eps=20).fit(Data)
labels2 = clustering2.labels_
print("Labels DBSCAN", labels2[:50])   

#Lijkt me dat beide problemen hier liggen aan de variabelen in de functies

# Birch clustering
#TODO nog een groot aantal clusters...
clustering3 = Birch(n_clusters=None).fit(Data)
labels3 = clustering3.labels_
print("Labels Birch", labels3[:50])   
aantal_clusters = len(set(labels3))
print("Aantal clusters Birch", aantal_clusters)


c:\users\friso\appdata\local\programs\python\python38\lib\site-packages\sklearn\cluster\_affinity_propagation.py:142: ConvergenceWarning:

Affinity propagation did not converge, this model may return degenerate cluster centers and labels.



Number of clusters: 176
Cluster centers:
 [[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [1. 5. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 1. 0. 0.]]
Labels DBSCAN [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 26  0  0  0 -1  0  0  0  0
  0  0  1  0  0 -1  0  0  0  0  0 20  0  0  0  0 -1  0  0  0  0  0  0  0
  0  0]
Labels Birch [  494  1737   341   154  5833  2060   458   155   993  7107  4304  5516
  3881  2390  1811 10977   342  4470  1012 11563  2160   156  2434   721
   419  2293 10717  1423  1738 10969   994  1424  3690  2707  4357 11562
  4316  3838  1739  5517 11449   931  4604  1013  1329  6150  3691  1468
  6633   343]
Aantal clusters Birch 12096


In [11]:
#TODO visualisaties van task 3
# in apart codeblock 

Task 4

In [13]:
# manual Silhouette score, is zo volgensmij goed. Moet alleen zoeken hoe ik deze waardes kan pakken uit de labels
import numpy as np
def Silhouette_score(point, labelSELF, labels, Data):
    clusterSELF = Data[labels == labelSELF].to_numpy()
    clusters = Data[labels != labelSELF].to_numpy()
    afstand = 0

    for points in clusterSELF:
        if set(points) == set(point):
            continue
        afstand += np.linalg.norm(point-points)
    a = afstand/len(clusterSELF)

    lowest = 999999999
    clustr = None
    for clust in clusters:
        afstand_nearest = 0
        for points in clust:
            afstand_nearest += np.linalg.norm(point-points)
        dis = afstand_nearest/len(clust)
        if dis < lowest:
            lowest = dis
            clustr = clust
    b = lowest
    return (b-a)/(max(b,a))

def Silhouette_scores(x, labels):
    n = len(x)
    sil_values = []
    for i in range(n):
        sil_values.append(Silhouette_score(point=x.iloc[i].to_numpy(), labelSELF = labels[i], labels = labels, Data= x))
    print("Silhouette score:", sil_values)

from sklearn.metrics import davies_bouldin_score
print("Silhouette scores:")
print(f"Affinity propagation: {Silhouette_scores(Sample, labels)}")
print(f"DBSCAN: {Silhouette_scores(Data[:1000], labels2[:1000])}")
print(f"Birch Clustering: {Silhouette_scores(Data[:1000], labels3[:1000])}")
print()

# Davies Buildin Score
from sklearn.metrics import davies_bouldin_score
print("Davies Bouldin score:")
print(f"Affinity propogation: {davies_bouldin_score(Sample, labels)}")
print(f"DBSCAN: {davies_bouldin_score(Data, labels2)}")
print(f"Birch Clustering: {davies_bouldin_score(Data, labels3)}")
print()
# calinski-harabasz index
from sklearn.metrics import calinski_harabasz_score
print("Calinski Harabasz score:")
print(f"Affinity propogation: {calinski_harabasz_score(Sample, labels)}")
print(f"DBSCAN: {calinski_harabasz_score(Data, labels2)}")
print(f"Birch Clustering: {calinski_harabasz_score(Data, labels3)}")

Silhouette scores:
Silhouette score: [1.0, 0.878736446749771, 0.7662484431530868, 0.7742817897861408, 0.8559688408548123, 0.8651070663856432, 0.8488157732650228, 1.0, 0.5017090279459387, 0.9101124486149625, 0.9643520914369468, 0.9332328992509247, 1.0, 0.9416626145018047, 0.9048491625736388, 0.22538804048262887, 0.8425444813996091, 0.9115544375353146, 0.781607933695057, 0.8649089598043697, 0.7188384382366519, 0.9002297825027985, 0.9215791996921291, 0.15624529209219484, 0.18190518222570262, 0.9633886754028588, 1.0, 0.7409260823370911, 0.5284083746125419, 1.0, 0.22451265203760906, 0.8861444525679153, 0.7880819519474844, 0.7681485163825628, 0.8341073592595727, 0.8843085345251915, 0.9262357892423178, 0.9017642999473482, 0.41602349757859997, 0.8200938893912628, 1.0, 1.0, 0.8364365920601684, 1.0, 0.9383146253162942, 0.1405826058333037, 0.8567189338327121, 0.9025150945380129, 0.6436352893952269, 0.40530132418574644, 0.9297880585380399, 0.9368441824296635, 0.7133637862350329, 0.9168833867469508

Task 5 ALL MANUAL


In [17]:
# dit is de basics, maar idk wat de dimensies van a en b horen te zijn
# Euclidean distance
def our_euclidean_distance(a, b):
    distance = 0
    for index, _ in enumerate(a):
        distance += (a[index] - b[index]) ** 2
    distance = distance**0.5
    return distance
# Manhattan distance
def our_manhattan_distance(a, b):
    distance = 0
    for index, _ in enumerate(a):
        distance += ((a[index] - b[index]) ** 0.5) ** 2
    return distance    
# Cosine similarity
def our_cosine_similarity(a, b):
    numerator = 0
    denominator_a = 0
    denominator_b = 0
    for index, _ in enumerate(a):
        numerator += a[index] * b[index]
        denominator_a += a[index] ** 2
        denominator_b += b[index] ** 2
    distance = numerator / (denominator_a ** 0.5 * denominator_b ** 0.5)
    return distance
# Distances effect on dbscan
clustering_c1 = DBSCAN(eps=20, metric=our_euclidean_distance).fit(Data[:1000])
label_c1 = clustering_c1.labels_
print("Labels DBSCAN", label_c1)   

clustering_c2 = DBSCAN(eps=200, metric=our_manhattan_distance).fit(Data[:1000])
label_c2 = clustering_c2.labels_
print("Labels DBSCAN", label_c2)   

clustering_c3 = DBSCAN(eps=20, metric=our_cosine_similarity).fit(Data[:1000])
label_c3 = clustering_c3.labels_
print("Labels DBSCAN", label_c3)   
import plotly.express as px
fig = px.scatter(Data[:1000], label_c2)
fig.show()

Labels DBSCAN [ 0  0  0  0  1  0  0  0  0  4  0  0  0  0  0 -1  0  0  0 -1  0  0  0  0
  0  0 -1  0  0 -1  0  0  0  0  0 -1  0  0  0  0 -1  0  0  0  0  1  0  0
  2  0  0  0  0  0  0  0  0 -1  0  0  0  0 -1  1  0 -1 -1  0  3  0  0  0
  0  0  0  1 -1  0  0  0  0  0  0  0  0  0  0  0  0  1 -1  0  0  1  3  0
 -1  0  0  1 -1 -1  0 -1 -1  0  0  0  0 -1  0  0  0 -1 -1  0 -1  1  0  0
  0  0 -1  0  0  0 -1  0 -1  0  0  0  0 -1 -1  0  0  0  0 -1  0  0  0  0
 -1  4  5  1 -1  0 -1  0  0  1  0  1  0  0  0  0  0 -1 -1  0  4  0  0  0
  1  1  0  0  0  0 -1 -1  1  0  0  0  0  0  0  0 -1  3 -1 -1 -1 -1  0 -1
 -1  0  0 -1 -1 -1 -1 -1 -1  0 -1  0 -1 -1 -1 -1 -1 -1 -1  1  0 -1 -1 -1
 -1 -1  0  0 -1  0  0 -1 -1  0 -1  0 -1 -1 -1 -1  0 -1 -1 -1 -1 -1  0 -1
 -1  0 -1 -1  4  1  2 -1 -1 -1 -1 -1  0  0  0 -1  0 -1 -1  0 -1  0 -1  0
  0 -1  0  0 -1  0  0  0 -1 -1  0  0 -1 -1 -1  1  0 -1 -1  0 -1  0  0 -1
 -1  0 -1 -1 -1  0 -1 -1  4 -1  0  0 -1 -1  0 -1  0  0  0  0  0 -1 -1  0
  0 -1 -1 -1  0 -1 -1 -1 -1  0  0 -1 

C:\Users\Friso\AppData\Local\Temp\ipykernel_12856\1660085157.py:13: RuntimeWarning:

invalid value encountered in scalar power



Labels DBSCAN [  0   2   0  -1  -1  -1   1  -1  -1  -1  -1  -1  17  62  92  -1   0  -1
   2  -1  -1  -1  39  -1  67   9  -1  12  -1  -1  50  -1  17  71  84  -1
  -1  -1  -1  -1  -1  -1  69  -1  -1  -1  -1   2  -1   4   3  -1  -1  -1
  -1   1   4  -1  -1  -1  -1  -1  -1  -1   5  -1  -1  -1  -1   4  -1  -1
  -1  -1   9  -1  -1  -1   6   1  -1  -1  18  -1  -1   0  -1   9  -1  37
  -1   3   2  -1  -1   2  -1  -1  -1  37  -1  -1  -1  -1  -1  -1  -1  -1
  -1  -1  -1   7   8  -1  -1  -1  -1  -1  -1   9   9  -1  -1  50  -1   0
  -1  -1  -1  -1  -1  -1   4  -1  -1  -1  -1  -1  -1  -1  10  -1  -1   1
  -1  -1  -1  -1  -1  -1  -1  11  -1  -1  33  -1  -1  -1   0   4  -1  -1
  -1  -1  -1  16  12  12  -1  -1  -1  -1  -1   6  -1  -1  37  -1   4  -1
  -1  13   1  -1  -1  -1  -1  -1  -1  -1  14  -1  -1  16  15  -1  -1  -1
  -1  -1  -1  45  -1  45  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
  -1  -1  16  -1  -1  -1  -1  -1  -1  -1  -1  35  -1  -1  -1  -1  -1  -1
  -1  -1  -1  -1  -1  -1  -1  17  -1 

In [20]:
clustering_c2 = DBSCAN(eps=2, metric=our_manhattan_distance).fit(Data[:1000])
label_c2 = clustering_c2.labels_
print("Labels DBSCAN", label_c2)   
clustering_c3 = DBSCAN(eps=20, metric=our_manhattan_distance).fit(Data[:1000])
label_c3 = clustering_c2.labels_
print("Labels DBSCAN", label_c3)   
clustering_c4 = DBSCAN(eps=20000, metric=our_manhattan_distance).fit(Data[:1000])
label_c4 = clustering_c4.labels_
print("Labels DBSCAN", label_c4)   

import plotly.express as px
fig = px.scatter(Data[:1000], label_c2)
fig.show()
fig = px.scatter(Data[:1000], label_c3)
fig.show()
fig = px.scatter(Data[:1000], label_c4)
fig.show()

C:\Users\Friso\AppData\Local\Temp\ipykernel_12856\1660085157.py:13: RuntimeWarning:

invalid value encountered in scalar power



Labels DBSCAN [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0 -1 -1
 -1 -1 -1 -1 -1 -1  1  1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  4
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1  0 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1  1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  2 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  3 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 

C:\Users\Friso\AppData\Local\Temp\ipykernel_12856\1660085157.py:13: RuntimeWarning:

invalid value encountered in scalar power



Labels DBSCAN [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0 -1 -1
 -1 -1 -1 -1 -1 -1  1  1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  4
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1  0 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1  1 -1 -1 -1 -1  0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  2 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  3 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 

C:\Users\Friso\AppData\Local\Temp\ipykernel_12856\1660085157.py:13: RuntimeWarning:

invalid value encountered in scalar power



Labels DBSCAN [  0   5   0  -1   1  46   2  -1  -1  -1  -1  -1   1 171 292  -1   0  11
   5  -1  -1  -1  96  -1 181  14  62   8  -1   3  14  -1   1 190   3  -1
   4  -1  -1 333  -1  -1  11  -1  -1  -1  26   5  42   7   6  -1  -1  -1
  -1   2   7  -1  -1  -1  11   8  -1  38   9  -1  -1  -1  -1   7  -1  -1
  -1  64  14  34  -1  -1  10   2  -1  11   1  -1  -1   0 104   8  -1  20
  11   6   5  -1  -1   5  -1  11  -1  96  -1  11  15  -1  -1  -1  -1  -1
  -1  -1  -1  12  13  -1  -1  11  -1  -1  -1  14  14  -1  15  14  -1   0
  16  -1  -1  -1  -1 120   7  -1  -1  64  64 244  -1  -1  17  11 191   2
 271  -1   3  -1  -1  -1   3  18  -1  -1  31 129  -1  -1   0   7  -1  -1
  -1  11  -1  15   1  19  -1  20  11  -1  -1  10  -1  62  23  -1   7  -1
  20  21   2  -1  -1 132  22  22  23  24  25  26  23  35  27  -1  -1  26
  -1  -1  -1 118 281 118 271 308  -1  28  -1  29  30  31  -1  32  33  -1
  -1  34  35  -1  -1 241  -1  -1  36  -1  22  44  -1  37  38  39  -1  40
  41  -1  42  43  52  44  45  46  47 